### PR TITLE
properly fix bug

### PR DESCRIPTION
**Pull request by CommandGenius**
The bug still appears. This fixes the issue when entering a menu and exiting.

### CODE REVIEW

**Comment by LunaticWasTaken** [comment]
Is there any specific case where this actually fixes anything?

From what i can see, your change immediately disables the focus again after it has been set, leaving only the hover-effect, which makes sliders look a little awkward when they're moved with the cursor outside of the actual widget bounds.

**Comment by CommandGenius** [comment]
> Is there any specific case where this actually fixes anything?
> 
> From what i can see, your change immediately disables the focus again after it has been set, leaving only the hover-effect, which makes sliders look a little awkward when they're moved with the cursor outside of the actual widget bounds.

I fixed the sliders issue. I'm testing this on 1.21 btw, and I made this PR because the mod was not working on 1.21 or 1.20.6 for me. Idk if it works properly on 1.20.2.

**Comment by CommandGenius** [comment]
Also the sliders disabled the focus effect when moving the mouse off of it in 1.19.3.

**Comment by LunaticWasTaken** [comment]
Interesting... For me, the mod is working 100% as intended on both 1.20.5 and 1.21. Can you confirm that this isn't an issue with a specific mod's widget? (see #4 for more info)


> Also the sliders disabled the focus effect when moving the mouse off of it in 1.19.3.

I see. Actually didn't even remember that. If you revert the 2nd and 3rd commit (i honestly have no idea if/how i can do that myself), i can merge it (as those changes won't be needed in that case), and then it should be exactly as it was in 1.19.3.

**Comment by CommandGenius** [comment]
> Interesting... For me, the mod is working 100% as intended on both 1.20.5 and 1.21. Can you confirm that this isn't an issue with a specific mod's widget? (see #4 for more info)
> 
> > Also the sliders disabled the focus effect when moving the mouse off of it in 1.19.3.
> 
> I see. Actually didn't even remember that. If you revert the 2nd and 3rd commit (i honestly have no idea if/how i can do that myself), i can merge it (as those changes won't be needed in that case), and then it should be exactly as it was in 1.19.3.

I just reverted the commits.

**Comment by CommandGenius** [comment]
Also, it's not a specific mods widgets.

**Comment by LunaticWasTaken** [comment]
merged, thanks.

**Pull request merged**
